// CONFIG DATA - Maps your cabs_clean folder structure.
// Generated by `npm run build:cabs-dataset` (scripts/build-cabs-dataset.mjs); do not hand-edit dataset.json.
import dataset from '../../public/cabs_clean/dataset.json';

export interface DoorOption {
  id: string;
  color: string;
  /** door swatch, relative to /cabs_clean/ */
  door: string;
  /** kitchen render, relative to /cabs_clean/ (null when no render exists yet) */
  kitchen: string | null;
  doorAlt: string | null;
  finish: string;
}
export interface DoorStyle {
  name: string;
  options: DoorOption[];
}
export interface HardwareFinishImages {
  pull: string;
  withDoor: string | null;
  sizeImages: { size: string; image: string }[];
  altImages: string[];
}
export interface HardwareStyle {
  name: string;
  description: string;
  finishes: Record<string, HardwareFinishImages>;
}
export interface DoorFinish {
  name: string;
  color?: string;
  texture?: string;
  roughness: number;
  textured: boolean;
}
export interface HardwareFinish {
  name: string;
  color: string;
  metalness: number;
  roughness: number;
}
export interface ConfigData {
  doorStyles: Record<string, DoorStyle>;
  doorFinishes: Record<string, DoorFinish>;
  hardware: Record<string, HardwareStyle>;
  hardwareFinishes: Record<string, HardwareFinish>;
  missing: string[];
}

export const CONFIG_DATA = dataset as unknown as ConfigData;

export const FINISH_COLORS: Record<string, string> = Object.fromEntries(
  Object.entries(CONFIG_DATA.hardwareFinishes).map(([k, v]) => [k, v.color]),
);
export const FINISH_NAMES: Record<string, string> = Object.fromEntries(
  Object.entries(CONFIG_DATA.hardwareFinishes).map(([k, v]) => [k, v.name]),
);

/** Public URL for a cabs_clean-relative path, with each segment URL-encoded (names contain spaces, parens). */
export function cabsUrl(relPath: string): string {
  return `/cabs_clean/${relPath.split('/').map(encodeURIComponent).join('/')}`;
}
