import * as THREE from 'three'

const paint = (color:string,roughness=.65,metalness=0) => new THREE.MeshStandardMaterial({color,roughness,metalness})
const chrome = () => paint('#c5cdd4',.25,.85)
// Bake the original meshes into a consistent, centered coordinate system.
function baked(source:THREE.Group) {
 source.updateMatrixWorld(true)
 const box=new THREE.Box3().setFromObject(source),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),scale=1/Math.max(size.x,size.y,size.z),root=new THREE.Group()
 source.traverse(o=>{const m=o as THREE.Mesh;if(!m.isMesh)return;const add=(matrix:THREE.Matrix4)=>{const geometry=m.geometry.clone().applyMatrix4(matrix);geometry.translate(-center.x,-center.y,-center.z);geometry.scale(scale,scale,scale);const mesh=new THREE.Mesh(geometry,Array.isArray(m.material)?m.material.map(x=>x.clone()):m.material.clone());mesh.name=m.name;root.add(mesh)};if((m as THREE.InstancedMesh).isInstancedMesh){const inst=m as THREE.InstancedMesh;for(let i=0;i<inst.count;i++){const mat=new THREE.Matrix4();inst.getMatrixAt(i,mat);add(new THREE.Matrix4().multiplyMatrices(m.matrixWorld,mat))}}else add(m.matrixWorld)})
 return root
}
function split(mesh:THREE.Mesh,materials:THREE.Material[],select:(v:THREE.Vector3)=>number){const geometry=mesh.geometry.index?mesh.geometry.toNonIndexed():mesh.geometry.clone(),positions=geometry.getAttribute('position'),buckets=materials.map(()=>[] as number[]),v=new THREE.Vector3();for(let i=0;i<positions.count;i+=3){v.set(0,0,0);for(let j=0;j<3;j++)v.add(new THREE.Vector3().fromBufferAttribute(positions,i+j));v.divideScalar(3);buckets[select(v)].push(i,i+1,i+2)}const indices:number[]=[];geometry.clearGroups();buckets.forEach((ids,material)=>{geometry.addGroup(indices.length,ids.length,material);indices.push(...ids)});geometry.setIndex(indices);mesh.geometry=geometry;mesh.material=materials}
function handle(root:THREE.Group,x:number,y:number,z:number,color='#22272b'){const material=paint(color,.3,.8),plate=new THREE.Mesh(new THREE.CylinderGeometry(.026,.026,.012,24),material);plate.rotation.x=Math.PI/2;plate.position.set(x,y,z);root.add(plate);const neck=new THREE.Mesh(new THREE.CylinderGeometry(.009,.009,.04,16),material);neck.rotation.x=Math.PI/2;neck.position.set(x,y,z+.025);root.add(neck);const lever=new THREE.Mesh(new THREE.CapsuleGeometry(.009,.067,4,12),material);lever.rotation.z=Math.PI/2;lever.position.set(x-.035,y,z+.05);root.add(lever)}
function curtainTexture(){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=256;const c=canvas.getContext('2d')!;c.fillStyle='#e87925';c.fillRect(0,0,256,256);for(let row=-1;row<5;row++){c.beginPath();for(let x=-32;x<=288;x+=32){const y=row*64+(Math.abs(x/32)%2)*24;x===-32?c.moveTo(x,y):c.lineTo(x,y)}c.lineWidth=14;c.strokeStyle=row%2?'#f7d6a9':'#ad4917';c.stroke()}const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=texture.wrapT=THREE.RepeatWrapping;return texture}
export function editMaterialModel(source:THREE.Group,id:number){const root=baked(source);const meshes=root.children as THREE.Mesh[];
 if(id===2){root.clear();const stone=paint('#e7e4df',.48),metal=chrome(),shape=new THREE.Shape();shape.moveTo(-.5,-.24);shape.lineTo(.5,-.24);shape.lineTo(.5,.24);shape.lineTo(-.5,.24);shape.closePath();const hole=new THREE.Path();hole.absellipse(-.10,0,.255,.165,0,Math.PI*2,true,0);shape.holes.push(hole);const slab=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:.055,bevelEnabled:true,bevelSize:.008,bevelThickness:.005,bevelSegments:2,steps:1,curveSegments:48}),stone);slab.rotation.x=-Math.PI/2;slab.position.y=-.05;root.add(slab);const vertices:number[]=[],indices:number[]=[];for(let row=0;row<=12;row++){const t=row/12,r=1-t*.45,y=-.04-.12*Math.sin(t*Math.PI/2);for(let i=0;i<=64;i++){const a=i/64*Math.PI*2;vertices.push(-.10+Math.cos(a)*.255*r,y,Math.sin(a)*.165*r);if(row<12&&i<64){const k=row*65+i;indices.push(k,k+1,k+65,k+1,k+66,k+65)}}}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geo.setIndex(indices);geo.computeVertexNormals();metal.side=THREE.DoubleSide;root.add(new THREE.Mesh(geo,metal));const bottom=new THREE.Mesh(new THREE.CircleGeometry(1,64),metal);bottom.rotation.x=-Math.PI/2;bottom.scale.set(.255*.55,.165*.55,1);bottom.position.set(-.1,-.16,0);root.add(bottom);const drain=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,.006,24),paint('#788790',.25,.8));drain.position.set(-.1,-.156,0);root.add(drain);const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(-.10,.005,-.20),new THREE.Vector3(-.10,.16,-.20),new THREE.Vector3(-.10,.20,-.13),new THREE.Vector3(-.10,.15,-.03)]);root.add(new THREE.Mesh(new THREE.TubeGeometry(curve,40,.012,12,false),metal));for(let i=0;i<2;i++){const cupmat=paint(i?'#c96e35':'#197d86',.28,.15),cup=new THREE.Mesh(new THREE.CylinderGeometry(.038,.03,.08,24,1,true),cupmat);cupmat.side=THREE.DoubleSide;cup.position.set(.31+i*.095,.045,-.10);root.add(cup);const base=new THREE.Mesh(new THREE.CylinderGeometry(.03,.03,.006,24),cupmat);base.position.set(cup.position.x,.008,-.10);root.add(base)}root.rotation.x=.65}
 if(id===3){meshes.forEach(m=>m.material=paint('#65717b',.65));handle(root,.22,-.13,.055,'#b9c6cf')}
 if(id===4){root.rotation.set(.32,Math.PI/2,0);for(const m of meshes){m.geometry.applyMatrix4(new THREE.Matrix4().makeRotationY(Math.PI/2));split(m,[paint('#174d59',.55),paint('#f3f1ed',.6),chrome()],v=>v.y>.13||v.z>.32?2:v.y<.045&&(Math.abs(v.x)>.23||v.z>.25||v.z<-.25)?0:Math.abs(v.x)<.23&&v.y<.065&&v.z<.25?2:1)}root.rotation.y=0}
 if(id===5||id===7){root.clear();const material=paint('#e8e4dc',.78),box=(w:number,h:number,d:number,x:number,y:number,z:number)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),w===.325?paint('#d4cec4',.8):material);m.position.set(x,y,z);root.add(m)};box(.405,1,.025,0,0,0);const panels=id===5?[{y:.22,h:.48},{y:-.08,h:.055},{y:-.31,h:.31}]:[{y:.19,h:.54},{y:-.32,h:.29}];for(const panel of panels){box(.325,panel.h,.008,0,panel.y,.017);for(const x of [-.17,.17])box(.018,panel.h+.03,.013,x,panel.y,.022);for(const y of [panel.y-panel.h/2-.006,panel.y+panel.h/2+.006])box(.35,.018,.013,0,y,.022)}handle(root,.16,-.10,.035)}
 if(id===9){const texture=curtainTexture();for(const m of meshes){if(/^Curtain_[12]_/.test(m.name)){const pos=m.geometry.getAttribute('position'),uv=new Float32Array(pos.count*2);for(let i=0;i<pos.count;i++){uv[i*2]=pos.getZ(i)*3;uv[i*2+1]=pos.getY(i)*3}m.geometry.setAttribute('uv',new THREE.BufferAttribute(uv,2));m.material=new THREE.MeshStandardMaterial({map:texture,roughness:.95,side:THREE.DoubleSide})}else m.material=/Rod|Ring/.test(m.name)?paint('#a9987a',.32,.65):paint('#eee8dd',.7)}root.rotation.y=-Math.PI/2}
 if(id===10)root.rotation.y=Math.PI/3
 if(id===11)root.rotation.x=.85
 if(id===14)root.rotation.set(.30,Math.PI/2,0)
 if(id===15)root.rotation.set(.45,Math.PI/2,0)
 // Export an oriented model; the stream can retain its small floating motion.
 root.updateMatrixWorld(true)
 return root
}
